### ISSUE TITLE
Add accesskeys

### ISSUE THREAD

**Issue by tonifisler** [swiss/styleguide#207]
![capture decran 2014-08-08 a 16 00 34](https://cloud.githubusercontent.com/assets/1708450/3857544/78651342-1f04-11e4-9042-a9a84f2c38f6.png)

Elements should use this kind of styles:

``` css
.hidden {
  display: inline;
  left: -1000px;
  overflow: hidden;
  width: 0px;
  position: absolute;
  top: -1000px;
  height: 0px 
}
```
