### ISSUE TITLE
Icons underlined on link:hover

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#398]
All links that have an icon before or after the link get underlined on hover. CSS fix in admin.css:

```scss
.icon.icon--after:after,.icon.icon--before:before,a.icon--after[data-toggle=collapse]:after,a[data-toggle=collapse]:before {
	font-family: 'Admin Icons';
	display: inline-block;
	text-decoration: underline; /* NEW : add code snippet */
	}

/* NEW add all the code snippet below */
.icon.icon--after:after,.icon.icon--before:before,a.icon--after[data-toggle=collapse]:after,a[data-toggle=collapse]:before,.icon.icon--after:hover:after,.icon.icon--before:hover:before,a.icon--after[data-toggle=collapse]:hover:after,a[data-toggle=collapse]:hover:before {
	text-decoration: none;
	}
```

![swissstyle-focus-icons-bug-001](https://cloud.githubusercontent.com/assets/9591815/10041900/362078fa-61e8-11e5-8690-a9c2d462b4f1.jpg)
![swissstyle-focus-icons-bug-002](https://cloud.githubusercontent.com/assets/9591815/10041901/3ef0e30c-61e8-11e5-8b71-5ee4a10ab35e.jpg)
