### ISSUE TITLE
Bootstrap grid and overflow issues on Tab Focus

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#399]
**Issue 1**: Bootstrap colums work with negative margins. That can cause design issues when working with fixed design elements like our Tab Focus. The `.tab-focus .tab-pane .col-sm-5` jumps out of border due to the negative -15px margin. with the padding of 15px the text just ends right at the border.

![swissstyle-focus-tab-bug-001](https://cloud.githubusercontent.com/assets/9591815/10042264/a2c25206-61ea-11e5-9e14-243bdee46d4b.jpg)

**Issue 2**: If the text is longer than the image height (which can be quite often in our case), the design get's screwed. That's an overflow issues.

![swissstyle-focus-tab-bug-002](https://cloud.githubusercontent.com/assets/9591815/10042485/aa618c1a-61eb-11e5-9b93-b0b2ab7ee21f.jpg)

**Issue 3**: Really bad get things when using long german words. Then the text jumps out of bounds on the right column or disappears in the nav tabs. 

![swissstyle-focus-tab-bug-003](https://cloud.githubusercontent.com/assets/9591815/10042553/1e798468-61ec-11e5-8f71-e014c9477f2b.jpg)

All issues can be fixed within CSS in admin.css:

``` scss
@media only screen and (min-width:768px) {
    .tab-focus .tab-pane .col-sm-5 {
        margin: 0 -30px 0 -15px !important; /* issue 1 */
        padding-left: 15px !important; /* issue 1 */
        height: 253px; /* issue 2 */
        overflow-y: auto; /* issue 2 */
        }
}

@media only screen and (min-width:992px) {
    .tab-focus .tab-pane .col-sm-5 {
        height: 245px; /* issue 2 */
    }

    .tab-focus .tab-pane .col-sm-5 h2 {
        -webkit-hyphens: auto; /* issue 3 */
            -ms-hyphens: auto;
           -moz-hyphens: auto;
                hyphens: auto;
        word-wrap: break-word; /* issue 3 */
    }
}

@media only screen and (min-width:1200px) {
    .tab-focus .tab-pane .col-sm-5 {
        height: 300px;  /* issue 2 */
    }
}

.nav-tabs.nav-tabs-focus li {
    -webkit-hyphens: auto;  /* issue 3 */
        -ms-hyphens: auto;
       -moz-hyphens: auto;
            hyphens: auto;
    word-wrap: break-word;  /* issue 3 */
}
```
